"""Update default business hours

Revision ID: 5398c65aa3ca
Revises: 26e8939ace24
Create Date: 2024-12-08 17:07:36.621842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5398c65aa3ca'
down_revision = '26e8939ace24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('email_password')
        batch_op.drop_column('email_use_tls')
        batch_op.drop_column('email_port')
        batch_op.drop_column('email_sender')
        batch_op.drop_column('email_server')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_server', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_sender', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_port', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('email_use_tls', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('email_password', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
