"""Add email settings

Revision ID: 789667d8a330
Revises: 1267b5fcbe24
Create Date: 2024-12-08 16:12:07.025048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789667d8a330'
down_revision = '1267b5fcbe24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sender', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_password', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_server', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email_use_tls', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('email_use_tls')
        batch_op.drop_column('email_port')
        batch_op.drop_column('email_server')
        batch_op.drop_column('email_password')
        batch_op.drop_column('email_sender')

    # ### end Alembic commands ###
